### ISSUE TITLE
Device registry firmware version doesn't seem to update

### ISSUE THREAD

**Issue by purcell-lab** [Teslemetry/hass-teslemetry#75]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

It would appear that the device registry isn't being updated with firmware revisions.

![Screenshot 2024-05-07 17 14 01](https://github.com/Teslemetry/hass-teslemetry/assets/79175134/930db665-c8e2-48e0-b4e0-fc16b9facd53)

Taken from the vehicle_data endpoint:

```
"vehicle_state": {
                "api_version": 75,
                "autopark_state_v2": "standby",
                "autopark_style": "standard",
                "calendar_supported": true,
                "car_version": "2024.8.9 0cac3042b6cd",
```

Yes this Intel vehicle is stuck with .14, my my other Rizen vehicle looks very nice.

### Reproduction steps

1. Check firmware in registry

**Comment by Bre77** [comment]
I think this is because I removed the version from the device registry. 

The reason I removed it was partially because it didn't update until Home Assistant restarted.

https://github.com/Teslemetry/hass-teslemetry/blob/54b9da01b991320d1ce0ee405832735d406cf4fe/custom_components/teslemetry/__init__.py#L101

You can see it because your device existed before it was removed.
