### ISSUE TITLE
Using service to set number.mycar_charge_limit to its current value gives error, blocks automation

### ISSUE THREAD

**Issue by fhteagle** [Teslemetry/hass-teslemetry#78]
### Checklist

- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/teslemetry/hacs-teslemetry/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Use call: service number:set on number.mycar_charge_limit to its current value returns an error "already_set". This blocks automations from proceeding.

Temporary workaround is to check the value of the charge limit in the automation before setting it, but this is unnecessary extra work. The integration should allow the existing value to be "set" (no change) and return no error instead.

### Reproduction steps

1. Note current number.mycar_charge_limit setting
2. Use automation call service action (or developer call service) number:set on number.mycar_charge_limit with value chosen to be the existing value
3. Note error "already set" is returned, which blocks automations from proceeding
...

### Debug logs

Nothing relevant in homeassistant.log (even with Teslemetry debug logging on), nor System > Logs

**Comment by Bre77** [comment]
The problem is, this is a response from Tesla, so I would have to hardcode in an exception to ignore this error, or just not make the API call at all if Home Assistant believes the value is the same, however this then causes other edge cases when you want to try change the value anyway.

It would be better for you to account for this in your automation by not calling the service if the value is the same, or adding `continue_on_error: true`.

I'll add a note about this in the documentation.

**Comment by Bre77** [comment]
Im having secound thoughts, I think I will ignore `already_set` errors.

**Comment by Bre77** [comment]
@fhteagle I am unable to reproduce this message on my Model 3. The fact your not seeing any logs suggests its failing sooner than I expected. Can you please turn on debug logs, reproduce the issue, then disable debug logs and send that through to me either here, email (admin@teslemetry.com), or Discord.

**Comment by fhteagle** [comment]
Well I figured out why there was not anything in the debug logs for this.

This in my configuration.yaml is not actually turning on debugging logging after a restart:

```
logger:
  default: warning
  logs:
    custom_components.teslemetry: debug
```

Even though that matched the log lines I got after turning on debug logging via GUI. What's the right logger component value(s) that you want debug output for ?  ```tesla_fleet_api``` also?

**Comment by fhteagle** [comment]
Oh and instead of ```continue_on_error: true``` , I implemented a workaround via template values to make sure the charge limit is always going to move at least 1.

Example:
```
service: number.set_value
data:
  value: >-
    {{ [[50, states('number.mycar_charge_limit')|int + 1,
    states('input_number.mycar_eco_charge_target')|int,
    states('input_number.mycar_calendar_charge_target_min')|int + 4 ] | max, 100
    ] | min }}
target:
  entity_id: number.mycar_charge_limit
```

Its a kludge at best, but it does work.

**Comment by fhteagle** [comment]
I just noticed the 1.9.5 pre-release and manually installed it (since it was not showing up in HACS even after a GUI force refresh). Looks like ignoring ```already_set``` did the trick, and the service call is proceeding even when sending the existing value.

**Comment by Bre77** [comment]
From my perspective, its still nicer if you dont make a pointless API call when the value wont change, but I also 100% get how much easier it is to just call it every time to be sure. The HA UI doesnt make the service call unless the value changes, but I dont want to code that into the integration because there may very well be situations where you need to force it.

1.9.5 was a pre-release, so you just have to tick the beta box in HACS I believe. It will be a general release after some more testing. I am glad the `already_set` fix seems to be working.
